<?php

namespace AppBundle\Repository;

/**
 * PlanetModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanetModelRepository extends \Doctrine\ORM\EntityRepository
{
}
